# Generated by Django 3.2.9 on 2022-01-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=500)),
                ('summary', models.CharField(max_length=5000)),
                ('image', models.FilePathField(default='', path='/home/access/Documents/Django/Django_Projects/myPortfolio/myportfolio/static/img')),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('github_link', models.URLField()),
                ('insta_link', models.URLField()),
            ],
        ),
    ]
