# Generated by Django 3.2.9 on 2022-01-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportapp', '0002_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('github_link', models.CharField(max_length=2000)),
                ('tech_stack', models.CharField(max_length=500)),
                ('image', models.FilePathField(default='', path='/home/access/Documents/Django/Django_Projects/myPortfolio/myportfolio/static/img')),
            ],
        ),
    ]
