# Generated by Django 3.2.9 on 2022-01-11 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportapp', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=2000)),
                ('published_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('is_present', models.BooleanField(blank=True, null=True)),
                ('responsibilities_1', models.CharField(blank=True, default=None, max_length=2000)),
                ('responsibilities_2', models.CharField(blank=True, default=None, max_length=2000)),
                ('responsibilities_3', models.CharField(blank=True, default=None, max_length=2000)),
                ('company', models.CharField(blank=True, default=None, max_length=200)),
                ('location', models.CharField(blank=True, default=None, max_length=200)),
            ],
        ),
    ]
