# Generated by Django 3.2.9 on 2022-01-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportapp', '0004_blog_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
