# Generated by Django 3.2.9 on 2022-01-17 06:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportapp', '0006_auto_20220113_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
